### ISSUE TITLE
3rd Party Media Hosting

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/deer-LR#126]
The Lived Religion project team wants to know if there are preferred media hosting solutions (Flickr, Google Photo, Dropbox, etc.).  The Lived Religion developers say whichever one has the most usable API is preferred.  The developers should look into the various APIs and see if one is better than the others, then advise.

**Comment by cubap** [comment]
Refer to doc emailed April 13 from Shruthi Sreenivasa Murthy
