### ISSUE TITLE
Interface: describe an experience

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/deer-LR#14]
Given a new experience, add annotations in the Bodies category to describe it. A separate interface will be provided for generating objects and persons that would be associated with them.

**Comment by thehabes** [comment]
Annotations to describe the experience that did not fit under a Spaces, Objects, or Body classification.  Are these to describe the user who is submitting?  They don't seem like they are describing the experience...

- Religious Tradition [Multi Choice]
   - Christian
      - Evangelical Protestant
      - Mainline Protestant
      - Historically Black Protestant
      - Catholic
      - Mormon
      - Orthodox Christian
      - Jehovah’s Witness
      - Other Christian
   - Jewish
      - Conservative
      - Reform
      - Orthodox
      - Reconstructionist
      - Other
   - Muslim
   - Buddhist
   - Daoism
   - Confucianism
   - Hindu
   - Sikh
   - Pagan
   - Indigenous
   - Native American Traditions
   - Other Religions
   - Other Faiths
   - Unaffiliated
   - Atheist
   - Agnostic
   - Humanist
   - Nothing in particular

- Race and Ethnicity [Multi Choice]
   - African American/Black/African
   - Bosniak
   - Caribbean
   - East Asian
   - Hispanic/Latinx
   - Middle Eastern
   - Native American/indigenous American
   - North African/Mediterranean
   - Pacific Islander
   - South Asian
   - Mixed-race
   - Other [show text input for description]

- Gender and Sexuality [Multi Choice]
   - Female-presenting
   - Male-presenting
   - Mostly cisgender mixed
   - Mostly transgender or queer
   - Mix of transgender, queer, and cisgender
   - Genders are intermingled
   - Genders are separated
   - Other [add required text box if checked]
   - Not applicable

- Education [check all that apply]
   - Some high school
   - High school graduate
   - Some college
   - College degree
   - Post-baccalaureate degree
