### ISSUE TITLE
<deer-view>s in <options>s

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/deer-LR#149]
HTML `<option>` tags generated programmatically look great in Template Literals.

When drawn to the DOM, any HTML inside `<option>` tags is stripped for its innerHTML.  So the following example <b>does NOT</b> result in a muti-select populated with the "most up to date label" as its options

```javascript
let primitiveLabel = UTILS.getLabel(person)
let labelHelperView = `<deer-view deer-id="${person["@id"]}" deer template="mostUpToDateLabelHelper">${primitiveLabel}</deer-view>`
tmpl += `<option deer-id="${person['@id']}" value="${person['@id']}">${labelHelperView}</option>`
```

The same scenario, but to populate a list (`<ul>`) <b>DOES</b> result in a list with showing the "most up to date labels"
```javascript
let primitiveLabel = UTILS.getLabel(person)
let labelHelperView = `<deer-view deer-id="${person["@id"]}" deer-template="mostUpToDateLabelHelper">${primitiveLabel}</deer-view>`
tmpl += `<li deer-id="${person['@id']}" value="${person['@id']}">${labelHelperView}</li>`
```

Is there a way around this behavior with `<option>` HTML Elements?
Is there another HTML Element we can use as a solution for multi-select scenarios (ex. checkbox groups)?
Do we need to rethink how Templates work?

See it for yourself
http://lived-religion-dev.rerum.io/deer-lr/people.html
http://lived-religion-dev.rerum.io/deer-lr/experience.html  check out the list of people...
Track around
deer-render.js RENDER.element

**Comment by cubap** [comment]
You probably already know this, but <option> tags cannot have other tags inside of them. That's important enough to be true. I've hit this in the Genealogger. You can rewrite the options elements without much cost, but they are essentially fancy text nodes, only containing text. I got around it by generating a hidden list and simply transforming it into the options of the <select> after it updated.

**Comment by thehabes** [comment]
Gotta to go to all the places where `<option>`a are being generated programmatically with the `<deer-view deer-template="mostUpToDateLabel">` helper inside the tag.  The DOM strips this HTML.

Instead, make the the generated option tag `<option class="deer-view" deer-template="label">`, there is no need to put HTML inside the option, and DEER will naturally handle the label.

As a bonus, we can delete the template `mostUpToDateLabelHelper` from the Lived Religion code.

**Comment by thehabes** [comment]
Closing as wontfix and will open another ticket addressing the issue correctly.
