### ISSUE TITLE
Data Entry Collection Views

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/deer-LR#183]
Do we need to expose these collections on the data entry pages [object.html, place.html, researcher.html, person.html]?

There is administrator handling tied to the views right now for removing collection items (and perhaps some other small things).  There was an undefined error that a hotfix took care of by commenting out `for (let elem of event.target.querySelectorAll('.removeCollectionItem')) elem.style.display = 'inline-block'` on all the data collection interfaces.

It is possible the administrator handling no longer needs to happen.  Let's look to clean this out.

**Comment by cubap** [comment]
remove the "current collection" at the bottom of the entry forms.
