### ISSUE TITLE
Encoding: The Experience

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/deer-LR#20]
The `Experience` object represents a data capture session where a user is uploading information in response to some encounter.  We will use the schema.org [Event](https://schema.org/Event) to encode this
```javascript
{
   "@type":"Event", 
   "location" : "A Place",
   "contributor":["researchers involved in the experience"],
   "startDate":"The date on which the Event occurred",
}
```

**Comment by thehabes** [comment]
This is necessary for #14

**Comment by cubap** [comment]
worth saying:

` "contributor" : [ "URI", "URI", "URI" ], `

and

` "creator" : "USER_URI" `

which is how we get a user having their own experiences.
