### ISSUE TITLE
Release v0.1

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/deer-LR#25]
Get the initial release out the door

- Lived Religion RERUM Dev Registration
- Lived Religion RERUM Prod Registration
- Make dev Researcher Agents 
- Make prod Researcher Agents
- Set up dev Lived Religion users file
- Set up prod Lived Religion users file
- Put both users files on the T;/ drive
- Test Lived Religion TinyThings Back End, make changes on `interfaces` branch if necessary
- DEER config must use ^^ LRTTBE
- Make sure `interfaces` branch contains all of our work
- PR `interfaces` branch to `master` branch
- Create `release` branch from `master` branch at this point
- Set up dev DNS and deploy on SLU dev, include users file
- Set up prod DNS and deploy on SLU prod, include users file
- Test, repeat whatever is necessary

**Comment by thehabes** [comment]
See blocking issue CenterForDigitalHumanities/rerum_server#90

See related issues CenterForDigitalHumanities/rerum_server#91 and CenterForDigitalHumanities/rerum_server#92

**Comment by thehabes** [comment]
Most items are complete, except those of which are blocked.  Still need to 

- Lived Religion RERUM Dev Registration
- Lived Religion RERUM Prod Registration
- Make sure interfaces branch contains all of our work
- PR interfaces branch to master branch
- Create release branch from master branch at this point
- Build and run `release` on dev for testing
- Stage for prod
- Build and run `release` on prod for testing

all work is in the `release_interfaces` branch

**Comment by cubap** [comment]
@thehabes the #Interfaces branch has the login components in it now and you should be able to test logging in on the pages.

**Comment by thehabes** [comment]
`interfaces` now has everything.  It is deployed for testing at
http://lived-religion-dev.rerum.io

**Comment by thehabes** [comment]
`release` has been created.  It is what is currently deployed.  Any fixes or improvements for getting it ready to release on prod should happen on this `release` branch.

**Comment by cubap** [comment]
`/login` is 404 here. Is something missing?

**Comment by thehabes** [comment]
fetch('login') instead of fetch('/login')

**Comment by cubap** [comment]
right, because it is in an app folder here. I'll get that right quick.

**Comment by cubap** [comment]
up in interfaces now.

**Comment by thehabes** [comment]
I literally did the same thing for every fetch URL because I put the `/` in the DEER.URLS enum.  Dont feel bad.

**Comment by thehabes** [comment]
Will deploy

**Comment by thehabes** [comment]
It is deployed.

**Comment by cubap** [comment]
Okay, I think we're looking good. The new_schema.html is also renamed.

**Comment by thehabes** [comment]
great, will prepare a deploy.

**Comment by thehabes** [comment]
It is up

**Comment by thehabes** [comment]
Almost all code is in interfaces and tested.  We should do a dev deploy and another tested after we bring in #29.
