### ISSUE TITLE
Ordering lists 

### ISSUE THREAD

**Issue by park353** [CenterForDigitalHumanities/deer-LR#255]
Hi Bryan and Patrick. Figured I'd start listing issues, technical or otherwise, as they arise here. We are folding in feedback as it comes. The fist is that the lists of experiences, locations, people, researchers, etc. are in no particular order. Could we alphabetize those for now? Perhaps add some other filtering/ordering options later?

**Comment by thehabes** [comment]
Hi Adam!  Yes, do this as you please.

You are correct in noticing there is no particular order.  I agree, alphabetized for now would be just fine, adding filter options for all those rendered list is a bit extra.  When I tackle this I will split that thought off into a new issue.
