### ISSUE TITLE
Map coordinates 

### ISSUE THREAD

**Issue by park353** [CenterForDigitalHumanities/deer-LR#258]
After typing in coordinates for a location, hitting "enter" saves the location entry, rather than taking one to the coordinates on the map view.

**Comment by thehabes** [comment]
oo that's a form focus thing.  It must not override that default action for an HTML form.  That's a small bug I will get that.

**Comment by park353** [comment]
Down the road, it may be helpful to add a "Find" button somewhere here, that users can click after entering in coordinates, addresses, cities, buildings, etc. Anyway, longer game.
