### ISSUE TITLE
Select additional things dropdown menus

### ISSUE THREAD

**Issue by park353** [CenterForDigitalHumanities/deer-LR#263]
When entering a new experience, one has the choice of selecting additional researchers, people, and objects. Once the drop down menu is clicked, one cannot un-select the highlighted researcher, people, or object. And these appear to be added to the entry.

**Comment by park353** [comment]
A similar thing is true when one is entering a new person. Once selected, the dropdown menus of religion, race, gender, and education cannot be unselected.

**Comment by thehabes** [comment]
I have added a "None" or "N/A" selection for all drop downs (I think I got them all...).  This is what you choose to "unselect" when you have previously made a selection.

**Comment by thehabes** [comment]
In the multi-select scenarios, it is a browser standard that you hold `ctrl` while you click to de-select an option.
