### ISSUE TITLE
adding new user

### ISSUE THREAD

**Issue by park353** [CenterForDigitalHumanities/deer-LR#273]
Using Firefox browser. New users could only be added after closing browser tab, then opening the app in a new tab to enter new user.

**Comment by thehabes** [comment]
Does this happen every time or was it a one off?

**Comment by thehabes** [comment]
Ah I was able to replicate.  I added one user OK, but when I went to add another user I couldn't.

**Comment by park353** [comment]
Yep. Exactly. Thanks.
