### ISSUE TITLE
Visual Feedback after success

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/deer-LR#70]
object, researcher, location, experience, delete from collections

**Comment by thehabes** [comment]
On object, researcher, location, person, researcher, i force a page refresh after a couple seconds.  We need to handle pagination in these pages still and probably implement some loading spinnies, and soon now that data collection is growing.

**Comment by thehabes** [comment]
I would like to push us to have something for this by end of day 12/20 that we can push to prod so users have it for over break.
